spring:
  application:
    name: Web Library

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springuser
    password: ThePassword
    url: jdbc:mysql://localhost:3306/web_library

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8080
  error:
    include-message: always